# Generated by Django 6.0.6 on 2026-07-04 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_jobapplication"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Client",
        ),
    ]
